import assert from 'node:assert/strict';
import {initial,mutate,today,addDays} from '../lib/pms.ts';
import {runAutomation,ensureAutomation} from '../lib/automation.ts';
import {parseCalendar,mergeCalendar,exportCalendar,externalBlocks,simulateChannels,validateCalendarUrl} from '../lib/channels.ts';
const now=new Date(),t=today();
let s=mutate(initial(),'booking',{unit:'v1',guest:'Test reminder',start:addDays(t,1),end:addDays(t,3),guests:2,channel:'Langsung',total:3000000});
s=runAutomation(s,now);assert.equal(s.automation.notices.length,2);assert.equal(s.tasks.length,1);
const twice=runAutomation(s,now);assert.equal(twice.automation.notices.length,2);assert.equal(twice.tasks.length,1);
const id=s.bookings[0].id;s=runAutomation(mutate(s,'payment',{id,type:'payment',amount:3000000,method:'Transfer',date:t}),now);
assert.equal(s.automation.notices.find(x=>x.rule==='paymentReminder').status,'resolved');
s=runAutomation(mutate(s,'booking',{...s.bookings[0],unit:'v2'}),now);
assert.equal(s.tasks.find(x=>x.unit==='v1').status,'Dibatalkan');assert.equal(s.tasks.find(x=>x.unit==='v2').status,'Belum dikerjakan');
s=runAutomation(mutate(s,'automation-schedule',{unit:'v3',title:'Servis AC',intervalDays:30,nextDue:addDays(t,-65),assignee:'Tim'}),now);
assert.equal(s.automation.schedules[0].nextDue,addDays(t,25));assert.equal(s.tasks.filter(x=>x.kind==='Maintenance').length,1);
assert.equal(runAutomation(s,now).tasks.filter(x=>x.kind==='Maintenance').length,1);
const paused=initial();ensureAutomation(paused).rules.arrivalPreparation.enabled=false;ensureAutomation(paused).rules.paymentReminder.enabled=false;paused.bookings=structuredClone(s.bookings);assert.equal(runAutomation(paused,now).tasks.length,0);
let channel=simulateChannels(initial(),'v7','create');const source=channel.channels.connections.find(c=>c.ota==='Airbnb');const others=channel.channels.connections.filter(c=>c.id!==source.id);
assert.equal(externalBlocks(channel,'v7').length,1);assert.equal(externalBlocks(channel,'v6').length,0);
for(const c of others){const text=exportCalendar(channel,c.id);assert.ok(text.includes('BEGIN:VEVENT'));assert.ok(!text.includes('Test reminder'));assert.deepEqual(parseCalendar(text),[],'Ignore our exported UIDs to prevent echoes');}
assert.ok(!exportCalendar(channel,source.id).includes('BEGIN:VEVENT'),'Do not echo a source back to itself');
assert.throws(()=>mutate(channel,'booking',{unit:'v7',guest:'Conflict',start:addDays(t,1),end:addDays(t,3),guests:2,channel:'Langsung',total:1}),/diblokir/);
channel=simulateChannels(channel,'v7','move');assert.equal(channel.channels.events.length,1);assert.equal(channel.channels.events[0].start,addDays(t,4));
channel=simulateChannels(channel,'v7','cancel');assert.equal(externalBlocks(channel,'v7').length,0);for(const c of others)assert.ok(!exportCalendar(channel,c.id).includes('BEGIN:VEVENT'));
const raw=['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT','UID:OTA-123','DTSTART;VALUE=DATE:20261010','DTEND;VALUE=DATE:20261012','SUMMARY:Reserved','END:VEVENT','END:VCALENDAR'].join('\r\n');
const parsed=parseCalendar(raw);assert.equal(parsed[0].start,'2026-10-10');mergeCalendar(channel,source.id,parsed);mergeCalendar(channel,source.id,parsed);assert.equal(channel.channels.events.filter(e=>e.uid==='OTA-123').length,1);
assert.throws(()=>parseCalendar('<html>Error</html>'),/iCal/);assert.throws(()=>parseCalendar(raw.replace('20261010','20260230')),/Tanggal/);assert.throws(()=>parseCalendar(raw.replace('SUMMARY:Reserved','RRULE:FREQ=DAILY')),/berulang/);assert.throws(()=>parseCalendar(raw.replace('END:VCALENDAR','')),/iCal/);
assert.throws(()=>validateCalendarUrl('Airbnb','http://localhost/calendar'),/HTTPS/);assert.throws(()=>validateCalendarUrl('Airbnb','https://airbnb.com.evil.example/calendar'),/HTTPS/);assert.throws(()=>validateCalendarUrl('Agoda','https://www.agoda.com/calendar'),/adapter/);
assert.equal(validateCalendarUrl('Airbnb','https://www.airbnb.com/calendar/ical/test.ics'),'https://www.airbnb.com/calendar/ical/test.ics');
console.log('PASS: automation deduplication, payment resolution, moved preparation, recurring catch-up, paused rules; A-to-B/C/D feeds, source exclusion, no echoes, date changes, cancellation, collision checks, iCal validation and URL restrictions.');
