import assert from 'node:assert/strict';
import {initial,mutate,today,addDays,paid} from '../lib/pms.ts';
const t=today();const booking={unit:'v1',guest:'Test Guest',start:t,end:addDays(t,2),guests:2,channel:'Langsung',total:3000000};
let s=mutate(initial(),'booking',booking);const id=s.bookings[0].id;
assert.throws(()=>mutate(s,'booking',booking),/sudah dipesan/);
assert.throws(()=>mutate(s,'booking',{...booking,unit:'v2',end:t}),/Check-out/);
assert.throws(()=>mutate(s,'booking',{...booking,unit:'v2',guests:99}),/kapasitas/);
assert.throws(()=>mutate(s,'booking',{...booking,unit:'v2',start:'2026-02-30'}),/Tanggal/);
assert.equal(mutate(s,'booking',{...booking,start:addDays(t,2),end:addDays(t,3)}).bookings.length,2);
s=mutate(s,'payment',{id,type:'payment',amount:1000000,method:'Transfer',date:t});
assert.equal(paid(s,id),1000000);
assert.throws(()=>mutate(s,'payment',{id,type:'refund',amount:1000001,method:'Transfer',date:t}),/Refund/);
s=mutate(s,'payment',{id,type:'deposit',amount:500000,method:'Transfer',date:t});
assert.equal(paid(s,id),1000000);
assert.throws(()=>mutate(s,'payment',{id,type:'deposit-return',amount:500001,method:'Transfer',date:t}),/deposit/);
s=mutate(s,'status',{id,status:'Checked-in'});
s=mutate(s,'status',{id,status:'Checked-out'});
assert.equal(s.units[0].clean,'Perlu dibersihkan');assert.equal(s.tasks.length,1);
s=mutate(s,'task-status',{id:s.tasks[0].id,status:'Selesai'});assert.equal(s.units[0].clean,'Siap');
const blocked=mutate(initial(),'block',{unit:'v1',start:t,end:addDays(t,3),reason:'Perbaikan'});
assert.throws(()=>mutate(blocked,'booking',booking),/diblokir/);
const held=mutate(initial(),'booking',{...booking,hold:true});held.bookings[0].holdUntil='2000-01-01T00:00:00Z';
assert.equal(mutate(held,'booking',booking).bookings.length,2);
assert.equal(initial().bookings.length,0);assert.ok(initial(true).bookings.length>0);
assert.equal(mutate(s,'unit',{id:'v1',name:'Vila Baru',rate:5000000,capacity:4}).bookings[0].total,3000000);
console.log('PASS: overlap, adjacent stays, date/capacity validation, payments, refund/deposit limits, checkout housekeeping, maintenance block, hold expiry, demo isolation, historical rates.');
