'use client';
import {useState} from 'react';
import {Zap,Wallet,CalendarCheck,LogOut,Brush,Clock,RefreshCw,Plus,Copy,Check,ArrowUpRight,Wrench,Bell,History,Pause,Play} from 'lucide-react';
import type {State} from '../lib/pms';
import {today} from '../lib/pms';
import {defaultAutomation,ruleNames} from '../lib/automation';
import type {RuleKey,Notice,Schedule} from '../lib/automation';
const descriptions:Record<RuleKey,string>={paymentReminder:'Buat pengingat dan draf pesan untuk reservasi yang masih memiliki sisa tagihan.',arrivalPreparation:'Buat tugas pemeriksaan kesiapan unit dan draf pesan sebelum kedatangan tamu.',checkoutReminder:'Siapkan pengingat waktu check-out untuk tamu yang sedang menginap.',checkoutCleanup:'Buat tugas pembersihan segera setelah reservasi diubah menjadi check-out.',holdExpiry:'Tandai hold yang habis waktunya sebagai kedaluwarsa. Tanggal tetap dilepas otomatis saat batas waktu lewat.'};
const icons={paymentReminder:Wallet,arrivalPreparation:CalendarCheck,checkoutReminder:LogOut,checkoutCleanup:Brush,holdExpiry:Clock};
const shortTime=(v:string)=>new Date(v).toLocaleString('id-ID',{timeZone:'Asia/Makassar',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
export default function AutomationPanel({state,busy,save,onBooking}:{state:State;busy:boolean;save:(action:string,payload:any)=>Promise<boolean|undefined>;onBooking:(id:string)=>void}){
 const a=state.automation||defaultAutomation();const [section,setSection]=useState('Aturan'),[draft,setDraft]=useState<Notice|null>(null),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(''),[schedule,setSchedule]=useState<Partial<Schedule>|null>(null),[showResolved,setShowResolved]=useState(false);
 const newCount=a.notices.filter(n=>n.status==='new').length;
 const savePlan=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));const ok=await save('automation-schedule',{...p,...(schedule?.id?{id:schedule.id}:{})});if(ok)setSchedule(null);};
 return <><div className="automation-intro"><div className="automation-symbol"><Zap size={25}/></div><div><h2>Operasional yang lebih teratur.</h2><p>Atur pemicu sekali. Pengingat dan tugas dibuat sesuai kondisi reservasi.</p></div><button className="primary" disabled={busy} onClick={()=>save('automation-run',{})}><RefreshCw size={16}/> Periksa sekarang</button></div><div className="automation-runtime"><Clock size={16}/><span>Diperiksa setiap menit selama aplikasi aktif, setelah perubahan data, dan saat dibuka kembali. Tidak berjalan saat aplikasi tertutup.</span><strong>{a.lastRun?'Terakhir '+shortTime(a.lastRun):'Belum diperiksa'}</strong></div><div className="automation-tabs">{[['Aturan',Zap],['Pengingat',Bell],['Perawatan berkala',Wrench],['Riwayat',History]].map(([name,Icon]:any)=><button key={name} onClick={()=>setSection(name)} className={section===name?'active':''}><Icon size={16}/>{name}{name==='Pengingat'&&newCount>0&&<b>{newCount}</b>}</button>)}</div>
 {section==='Aturan'&&<div className="automation-rules">{(Object.keys(ruleNames) as RuleKey[]).map(key=>{const rule=a.rules[key],Icon=icons[key];return <section className={'panel automation-rule '+(!rule.enabled?'paused':'')} key={key}><div className="rule-top"><span className="rule-icon"><Icon size={22}/></span><button role="switch" aria-label={'Aktifkan '+ruleNames[key]} aria-checked={rule.enabled} className={'toggle '+(rule.enabled?'on':'')} disabled={busy} onClick={()=>save('automation-rule',{key,enabled:!rule.enabled,daysBefore:rule.daysBefore})}><span/></button></div><h3>{ruleNames[key]}</h3><p>{descriptions[key]}</p><div className="rule-flow"><span>{key==='checkoutCleanup'?'Saat check-out':key==='holdExpiry'?'Batas 1 jam terlewati':`${rule.daysBefore} hari sebelum ${key==='checkoutReminder'?'check-out':'check-in'}`}</span><ArrowUpRight size={14}/><span>{key==='checkoutCleanup'?'Tugas kebersihan':key==='holdExpiry'?'Status kedaluwarsa':key==='arrivalPreparation'?'Tugas + draf pesan':'Pengingat + draf pesan'}</span></div>{!['checkoutCleanup','holdExpiry'].includes(key)&&<label className="rule-offset">Waktu pengingat<select aria-label={'Jeda '+ruleNames[key]} value={rule.daysBefore} disabled={busy} onChange={e=>save('automation-rule',{key,enabled:rule.enabled,daysBefore:Number(e.target.value)})}>{[0,1,2,3,7,14,30].map(n=><option key={n} value={n}>{n===0?'Pada hari yang sama':n+' hari sebelumnya'}</option>)}</select></label>}<div className="rule-status">{rule.enabled?<><Check size={13}/> Aturan aktif</>:<><Pause size={13}/> Dijeda</>}</div></section>})}<div className="panel automation-info"><Bell size={26}/><h3>Pesan tetap dalam kendali Anda</h3><p>Draf pesan muncul di tab Pengingat. Tinjau, salin, lalu kirim melalui kanal pilihan Anda.</p><small>WhatsApp dan email otomatis belum terhubung. Sistem tidak mengirim pesan kepada tamu.</small></div></div>}
 {section==='Pengingat'&&<section className="panel"><div className="panel-heading"><h2>Pengingat operasional <span className="sub-count">{newCount} baru</span></h2><label className="checkbox"><input type="checkbox" checked={showResolved} onChange={e=>setShowResolved(e.target.checked)}/> Tampilkan selesai</label></div>{a.notices.filter(n=>showResolved||n.status!=='resolved').length?a.notices.filter(n=>showResolved||n.status!=='resolved').map(n=><div className={'notice-row '+(n.status==='new'?'unread':'')} key={n.id}><span className="notice-icon"><Bell size={18}/></span><div className="notice-text"><h3>{n.title}</h3><p>{n.body}</p><small>{shortTime(n.created)} · {n.status==='new'?'Baru':n.status==='read'?'Sudah dilihat':'Selesai otomatis'}</small></div><div className="notice-actions"><button className="secondary" onClick={()=>{setDraft(n);setCopied(false);setCopyError('')}}>Lihat {n.rule==='holdExpiry'?'detail':'draf'}</button>{n.booking&&<button className="text-btn" onClick={()=>onBooking(n.booking!)}>Reservasi <ArrowUpRight size={14}/></button>}{n.status==='new'&&<button className="text-btn" disabled={busy} onClick={()=>save('automation-notice',{id:n.id,status:'read'})}><Check size={14}/> Tandai dilihat</button>}</div></div>):<div className="empty"><Check size={26}/><h3>Semua sudah tertangani</h3><p>Pengingat muncul otomatis ketika kondisi aturan terpenuhi.</p></div>}</section>}
 {section==='Perawatan berkala'&&<><div className="section-actions"><span>{a.schedules.filter(x=>x.enabled).length} jadwal aktif</span><button className="secondary" onClick={()=>setSchedule({unit:state.units[0].id,nextDue:today(),intervalDays:30,title:'',assignee:''})}><Plus size={16}/> Jadwal baru</button></div>{schedule&&<section className="panel"><div className="panel-heading"><h2>{schedule.id?'Ubah':'Tambah'} jadwal perawatan</h2><button className="text-btn" onClick={()=>setSchedule(null)}>Tutup formulir</button></div><form className="settings-form" key={schedule.id||'new'} onSubmit={savePlan}><div className="form-grid"><label className="field"><span>Nama pekerjaan</span><input required name="title" placeholder="Contoh: Servis AC" defaultValue={schedule.title} maxLength={300}/></label><label className="field"><span>Unit vila</span><select required name="unit" defaultValue={schedule.unit}>{state.units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label className="field"><span>Jadwal pertama / berikutnya</span><input required name="nextDue" type="date" defaultValue={schedule.nextDue}/></label><label className="field"><span>Ulangi setiap (hari)</span><input required name="intervalDays" type="number" min="1" max="365" defaultValue={schedule.intervalDays}/></label><label className="field"><span>Petugas (opsional)</span><input name="assignee" maxLength={100} defaultValue={schedule.assignee}/></label></div><div className="note">Saat jatuh tempo, tugas dibuat di Maintenance. Jika beberapa periode terlewat, satu tugas tertunda dibuat dan jadwal berikutnya dimajukan ke masa depan.</div><button className="primary" disabled={busy}>Simpan jadwal</button></form></section>}<section className="panel"><div className="table-wrap"><table><thead><tr><th>Pekerjaan</th><th>Unit</th><th>Pengulangan</th><th>Jadwal berikutnya</th><th>Status</th><th/></tr></thead><tbody>{a.schedules.map(p=><tr key={p.id}><td><strong>{p.title}</strong><small>{p.assignee||'Petugas belum diisi'}</small></td><td>{state.units.find(u=>u.id===p.unit)?.name}</td><td>Setiap {p.intervalDays} hari</td><td>{p.nextDue}</td><td><span className={'badge '+(p.enabled?'green':'amber')}>{p.enabled?'Aktif':'Dijeda'}</span></td><td><div className="inline"><button className="text-btn" onClick={()=>setSchedule(p)}>Edit</button><button className="text-btn" disabled={busy} onClick={()=>save('automation-schedule-toggle',{id:p.id,enabled:!p.enabled})}>{p.enabled?<Pause size={14}/>:<Play size={14}/>} {p.enabled?'Jeda':'Aktifkan'}</button></div></td></tr>)}</tbody></table>{!a.schedules.length&&<div className="empty"><Wrench size={28}/><h3>Belum ada jadwal perawatan</h3><p>Tambahkan servis AC, perawatan kolam, atau pemeriksaan fasilitas secara berkala.</p></div>}</div></section></>}
 {section==='Riwayat'&&<section className="panel"><div className="panel-heading"><h2>Hasil automatisasi</h2><span className="text-muted">Maksimal 500 aktivitas terbaru</span></div>{a.history.length?a.history.map(h=><div className="automation-history" key={h.id}><span className="history-check"><Check size={16}/></span><div><strong>{h.message}</strong><small>{ruleNames[h.rule as RuleKey]||'Perawatan berkala'}</small></div><time>{shortTime(h.time)}</time></div>):<div className="empty"><History size={28}/><h3>Belum ada aktivitas otomatis</h3><p>Riwayat muncul ketika sebuah aturan membuat pengingat atau tugas.</p></div>}</section>}
 {draft&&<div className="draft-panel"><div className="panel-heading"><h2>{draft.title}</h2><button className="text-btn" onClick={()=>setDraft(null)}>Tutup</button></div><div className="settings-form"><label className="field"><span>Draf untuk ditinjau dan disalin</span><textarea readOnly value={a.notices.find(n=>n.id===draft.id)?.body||draft.body} rows={6}/></label><div className="inline"><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(a.notices.find(n=>n.id===draft.id)?.body||draft.body);setCopied(true)}catch{setCopyError('Salin teks secara manual dari kotak di atas.')}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Tersalin':'Salin teks'}</button><small>Menyalin tidak mengirim pesan.</small></div>{copyError&&<p>{copyError}</p>}</div></div>}
 </>;
}

