'use client';
import {useState} from 'react';
import {Network,Plus,RefreshCw,ArrowRight,ArrowDownUp,ShieldCheck,AlertTriangle,Download,Pause,Play,Link2,Clock} from 'lucide-react';
import type {State} from '../lib/pms';
import {externalBlocks} from '../lib/channels';
export default function ChannelsPanel({state,demo,busy,save}:{state:State;demo:boolean;busy:boolean;save:(action:string,payload:any)=>Promise<boolean|undefined>}){
 const channels=state.channels||{connections:[],events:[],history:[]};const [add,setAdd]=useState(false),[ota,setOta]=useState('Airbnb'),[mode,setMode]=useState('ical'),[view,setView]=useState('Listing'),[selectedUnit,setSelectedUnit]=useState('v7'),[editUrl,setEditUrl]=useState<string|null>(null);
 const conflicts=channels.events.filter(e=>e.status==='active'&&state.bookings.some(b=>{const c=channels.connections.find(c=>c.id===e.connection);return b.unit===c?.unit&&['Confirmed','Checked-in'].includes(b.status)&&b.start<e.end&&b.end>e.start}));
 const dates=(d:string)=>new Date(d).toLocaleString('id-ID',{timeZone:'Asia/Makassar',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
 const name=(id:string)=>state.units.find(u=>u.id===id)?.name;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));if(await save('channel-add',p))setAdd(false)}
 return <><div className="channel-overview"><div><span className="eyebrow">SATU INVENTORI · BANYAK KANAL</span><h2>Reservasi masuk dari mana saja.<br/>Tanggal vila tetap satu.</h2><p>Setiap listing dipetakan ke unit fisik yang sama. Kalender keluar memuat blok dari PMS dan kanal lain, dengan sumber asal dikecualikan.</p></div><div className="channel-flow"><span>Airbnb · Booking.com<br/>Agoda · Traveloka</span><ArrowDownUp size={25}/><strong><Network size={21}/> Vila Eight</strong><small>8 unit · kalender terpusat</small></div></div><div className="channel-status"><ShieldCheck size={19}/><p><strong>Status: koneksi keluar belum aktif.</strong> Pemetaan API belum menghubungkan akun OTA. Impor iCal dapat menarik blok kalender setelah URL diisi. Pembaruan ke OTA lain membutuhkan feed yang dapat diakses OTA atau channel manager/API terkonfigurasi.</p></div>
 <div className="channel-stats"><div><strong>{channels.connections.length}</strong><span>Listing dipetakan</span></div><div><strong>{channels.connections.filter(c=>c.lastSync).length}</strong><span>Kalender pernah diimpor</span></div><div><strong>0</strong><span>Koneksi keluar terverifikasi</span></div><div><strong>{conflicts.length}</strong><span>Konflik dengan reservasi PMS</span></div></div>
 {demo&&<div className="channel-demo"><div><strong>Uji alur dengan data contoh</strong><small>Tidak terhubung ke OTA asli. Coba reservasi masuk, perubahan tanggal, dan pembatalan.</small></div><select aria-label="Unit simulasi OTA" value={selectedUnit} onChange={e=>setSelectedUnit(e.target.value)}>{state.units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><button className="secondary" disabled={busy} onClick={()=>save('channel-demo',{unit:selectedUnit,event:'create'})}>Booking Airbnb</button><button className="secondary" disabled={busy} onClick={()=>save('channel-demo',{unit:selectedUnit,event:'move'})}>Ubah tanggal</button><button className="secondary" disabled={busy} onClick={()=>save('channel-demo',{unit:selectedUnit,event:'cancel'})}>Batalkan</button></div>}
 <div className="automation-tabs">{['Listing','Kalender masuk','Riwayat sinkronisasi','Panduan koneksi'].map(n=><button className={view===n?'active':''} key={n} onClick={()=>setView(n)}>{n}</button>)}</div>
 {view==='Listing'&&<><div className="section-actions"><span>Airbnb, Booking.com, Agoda, Traveloka, dan kanal lainnya</span><button className="primary" onClick={()=>setAdd(!add)}><Plus size={16}/> Petakan listing</button></div>{add&&<section className="panel"><div className="panel-heading"><h2>Hubungkan listing ke unit vila</h2><button className="text-btn" onClick={()=>setAdd(false)}>Tutup</button></div><form className="settings-form" onSubmit={submit}><div className="form-grid"><label className="field"><span>Unit fisik</span><select required name="unit">{state.units.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label><label className="field"><span>OTA</span><select name="ota" value={ota} onChange={e=>{setOta(e.target.value);setMode(['Airbnb','Booking.com','Vrbo'].includes(e.target.value)?'ical':'api')}}>{['Airbnb','Booking.com','Agoda','Traveloka','Vrbo','Lainnya'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>ID / nama listing di OTA</span><input required name="listing" placeholder="Contoh: Villa Ocean — 123456" maxLength={150}/></label><label className="field"><span>Jalur integrasi</span><select name="mode" value={mode} onChange={e=>setMode(e.target.value)}>{['Airbnb','Booking.com','Vrbo'].includes(ota)&&<option value="ical">Kalender iCal</option>}<option value="api">Channel manager / API (belum dikonfigurasi)</option></select></label></div>{mode==='ical'?<><label className="field"><span>URL ekspor kalender dari OTA</span><input required type="url" name="url" placeholder="https://…" autoComplete="off"/></label><div className="note">Gunakan tautan ekspor kalender, bukan URL halaman listing. URL dipakai server untuk mengambil tanggal dan tidak ditampilkan kepada tamu. Jangan masukkan kata sandi akun OTA.</div></>:<div className="note">Langkah ini hanya menyimpan pemetaan listing. Adapter API dan akses dari penyedia channel manager masih diperlukan sebelum data dapat bertukar.</div>}<button className="primary" disabled={busy}>Simpan pemetaan</button></form></section>}
 <section className="panel"><div className="table-wrap"><table><thead><tr><th>Unit vila</th>{['Airbnb','Booking.com','Agoda','Traveloka','Lainnya'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{state.units.map(u=><tr key={u.id}><td><strong>{u.name}</strong></td>{['Airbnb','Booking.com','Agoda','Traveloka','Lainnya'].map(ota=>{const cs=channels.connections.filter(c=>c.unit===u.id&&(ota==='Lainnya'?!['Airbnb','Booking.com','Agoda','Traveloka'].includes(c.ota):c.ota===ota));return <td key={ota}>{cs.length?<span className="badge blue">{cs.length} dipetakan</span>:<span className="text-muted">—</span>}</td>})}</tr>)}</tbody></table></div></section><div className="channel-list">{channels.connections.map(c=><section className="panel channel-card" key={c.id}><div className="between"><div className="inline"><span className={'ota-avatar '+(c.ota==='Airbnb'?'airbnb':c.ota==='Booking.com'?'booking':'other')}>{c.ota.slice(0,1)}</span><div><h3>{c.ota}</h3><small>{name(c.unit)} · {c.listing}</small></div></div><span className={'badge '+(!c.enabled?'amber':c.error?'red':c.lastSync?'green':'amber')}>{!c.enabled?'Dijeda':c.error?'Perlu diperiksa':c.lastSync?'Impor berhasil':'Belum terhubung'}</span></div><div className="channel-detail"><div><small>JALUR</small>{c.mode==='ical'?'Kalender iCal':'Channel manager / API'}</div><div><small>IMPOR TERAKHIR</small>{c.lastSync?dates(c.lastSync):'Belum pernah'}</div><div><small>SINKRONISASI KELUAR</small>Belum aktif</div></div>{c.error&&<p className="error">{c.error}</p>}<div className="button-row">{c.mode==='ical'&&<button className="secondary" disabled={busy||!c.enabled} onClick={()=>save('channel-sync',{id:c.id})}><RefreshCw size={15}/> Tarik kalender</button>}<a className="secondary" href={'/api/calendar?demo='+(demo?1:0)+'&connection='+encodeURIComponent(c.id)} download><Download size={15}/> Unduh kalender keluar</a><button className="text-btn" disabled={busy} onClick={()=>save('channel-toggle',{id:c.id,enabled:!c.enabled})}>{c.enabled?<Pause size={15}/>:<Play size={15}/>} {c.enabled?'Jeda impor':'Aktifkan impor'}</button></div>{c.mode==='ical'&&<button className="text-btn" onClick={()=>setEditUrl(editUrl===c.id?null:c.id)}>Ubah URL kalender</button>}{editUrl===c.id&&<form className="settings-form" onSubmit={async e=>{e.preventDefault();const url=new FormData(e.currentTarget).get('url');if(await save('channel-update',{id:c.id,url}))setEditUrl(null)}}><label className="field"><span>URL ekspor kalender</span><input name="url" type="url" required defaultValue={c.url}/></label><button className="secondary" disabled={busy}>Simpan URL</button></form>}<small className="channel-footnote">File unduhan adalah salinan sesaat, bukan koneksi sinkronisasi otomatis. Blok yang sudah diimpor tetap dipertahankan ketika impor dijeda.</small></section>)}</div></>}
 {view==='Kalender masuk'&&<section className="panel"><div className="panel-heading"><h2>Tanggal dari OTA</h2></div><div className="note">iCal mengirim blok kalender, yang belum tentu berisi detail reservasi, harga, atau tamu. Blok ini mencegah pemesanan ulang di PMS dan masuk ke kalender keluar kanal lain.</div><div className="table-wrap"><table><thead><tr><th>Unit</th><th>Sumber</th><th>Tanggal</th><th>Keterangan</th><th>Status</th></tr></thead><tbody>{channels.events.map(e=>{const c=channels.connections.find(c=>c.id===e.connection);return <tr key={e.id}><td>{c?name(c.unit):'—'}</td><td>{c?.ota}</td><td>{e.start} — {e.end}</td><td>{e.summary}</td><td><span className={'badge '+(e.status==='cancelled'?'amber':conflicts.some(x=>x.id===e.id)?'red':'green')}>{e.status==='cancelled'?'Dilepas':conflicts.some(x=>x.id===e.id)?'Konflik PMS':'Memblokir tanggal'}</span></td></tr>})}</tbody></table>{!channels.events.length&&<div className="empty"><CalendarIcon/><h3>Belum ada kalender masuk</h3><p>Petakan listing lalu tarik kalender, atau coba simulasi dalam mode data contoh.</p></div>}</div></section>}
 {view==='Riwayat sinkronisasi'&&<section className="panel"><div className="panel-heading"><h2>Riwayat impor kalender</h2></div>{channels.history.map(h=><div className="automation-history" key={h.id}>{h.ok?<ShieldCheck size={18}/>:<AlertTriangle size={18}/>}<div><strong>{h.message}</strong><small>{channels.connections.find(c=>c.id===h.connection)?.ota||'Kalender'}</small></div><time>{dates(h.time)}</time></div>)}{!channels.history.length&&<div className="empty"><Clock size={26}/><h3>Belum ada sinkronisasi</h3><p>Hasil impor berhasil dan gagal akan tercatat di sini.</p></div>}</section>}
 {view==='Panduan koneksi'&&<section className="panel channel-guide"><h2>Untuk alur A → PMS → B, C, D</h2><ol><li>Petakan seluruh listing yang menjual vila fisik yang sama ke satu unit PMS.</li><li>Untuk iCal, masukkan URL ekspor setiap OTA dan jalankan tarik kalender. PMS menyimpan tanggal terblokir.</li><li>Kalender keluar tiap listing berisi reservasi PMS, blok manual, dan tanggal dari kanal lainnya. Sumber listing itu sendiri dikecualikan.</li><li>Aktifkan endpoint kalender yang dapat diakses OTA dan impor URL tersebut ke tiap OTA. Langkah ini belum aktif karena aplikasi masih privat dan belum diterbitkan.</li><li>Untuk Agoda, Traveloka, dan sinkronisasi yang lebih cepat, hubungkan penyedia channel manager/API yang mendukung akun Anda. Adapter API belum dikonfigurasi.</li><li>Uji pemesanan, perubahan, dan pembatalan pada akun uji sebelum mengandalkan penutupan tanggal otomatis.</li></ol><div className="note">Impor diperiksa berkala ketika aplikasi terbuka. Tidak ada penjadwal 24 jam saat ini. Kalender OTA dapat memperbarui dengan jeda; iCal tidak menjamin bebas overbooking. Jika OTA mengubah UID dan menghapus penanda ekspor, pemblokiran berulang perlu diperiksa.</div><p className="source-links">Referensi: <a target="_blank" rel="noreferrer" href="https://www.airbnb.com/help/article/99">Airbnb iCal</a> · <a target="_blank" rel="noreferrer" href="https://developers.booking.com/connectivity/docs">Booking.com Connectivity</a> · <a target="_blank" rel="noreferrer" href="https://partnerhub.agoda.com/how-do-i-manage-my-availability/">Agoda</a> · <a target="_blank" rel="noreferrer" href="https://tera.traveloka.com/id-id/partner/">Traveloka TERA</a></p></section>}
 </>;
}
function CalendarIcon(){return <Network size={26}/>}

