import type {State,Booking,Task} from './pms';
import {transitionBooking} from './booking-status.ts';
import {transitionTask} from './task-status.ts';

export type RuleKey='paymentReminder'|'arrivalPreparation'|'checkoutReminder'|'checkoutCleanup'|'holdExpiry';
export type Rule={enabled:boolean;daysBefore:number};
export type Notice={id:string;key:string;rule:string;booking?:string;title:string;body:string;status:'new'|'read'|'resolved';created:string;updated:string};
export type Schedule={id:string;unit:string;title:string;assignee:string;intervalDays:number;nextDue:string;enabled:boolean};
export type AutomationData={rules:Record<RuleKey,Rule>;schedules:Schedule[];notices:Notice[];history:{id:string;time:string;rule:string;message:string}[];lastRun:string|null};
const day=(time:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Makassar',year:'numeric',month:'2-digit',day:'2-digit'}).format(time);
const shift=(d:string,n:number)=>new Date(Date.parse(d+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
const rupiah=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const balance=(s:State,b:Booking)=>b.total-s.payments.filter(p=>p.booking===b.id).reduce((sum,p)=>sum+(p.type==='payment'?p.amount:p.type==='refund'?-p.amount:0),0);
export const ruleNames:Record<RuleKey,string>={paymentReminder:'Pengingat pelunasan',arrivalPreparation:'Persiapan check-in',checkoutReminder:'Pengingat check-out',checkoutCleanup:'Housekeeping setelah check-out',holdExpiry:'Hold kedaluwarsa'};
export function defaultAutomation():AutomationData{return {rules:{paymentReminder:{enabled:true,daysBefore:2},arrivalPreparation:{enabled:true,daysBefore:1},checkoutReminder:{enabled:true,daysBefore:1},checkoutCleanup:{enabled:true,daysBefore:0},holdExpiry:{enabled:true,daysBefore:0}},schedules:[],notices:[],history:[],lastRun:null}}
export function ensureAutomation(s:State){s.automation??=defaultAutomation();return s.automation}
export function automationLog(s:State,rule:string,message:string,time=new Date().toISOString()){const a=ensureAutomation(s);a.history.unshift({id:crypto.randomUUID(),time,rule,message});a.history=a.history.slice(0,500)}
function notice(s:State,n:Omit<Notice,'id'|'status'|'created'|'updated'>,time:string){const a=ensureAutomation(s);const existing=a.notices.find(x=>x.key===n.key);if(existing){if(existing.body!==n.body||existing.title!==n.title){existing.body=n.body;existing.title=n.title;existing.updated=time;}if(existing.status==='resolved'){existing.status='new';existing.updated=time;}return}a.notices.unshift({...n,id:crypto.randomUUID(),status:'new',created:time,updated:time});automationLog(s,n.rule,n.title,time)}
export function runAutomation(source:State,now=new Date()):State{const s=structuredClone(source);const a=ensureAutomation(s);const t=day(now),iso=now.toISOString();
 // Resolve reminders whose booking has changed; never claim a message was sent.
 for(const n of a.notices){if(!n.booking)continue;const b=s.bookings.find(b=>b.id===n.booking);if(!b||(n.rule==='paymentReminder'&&n.key!=='payment:'+b.id+':'+b.start)||(n.rule==='arrivalPreparation'&&n.key!=='arrival:'+b.id+':'+b.start+':'+b.unit)||(n.rule==='checkoutReminder'&&n.key!=='departure:'+b.id+':'+b.end)||['Cancelled','No-show','Expired','Checked-out'].includes(b.status)||(n.rule==='paymentReminder'&&balance(s,b)<=0)||(n.rule==='arrivalPreparation'&&b.status==='Checked-in'))n.status='resolved';}
 for(const b of s.bookings){const u=s.units.find(u=>u.id===b.unit);if(!u)continue;
  if(a.rules.holdExpiry.enabled&&b.status==='Hold'&&b.holdUntil&&Date.parse(b.holdUntil)<=now.getTime()){transitionBooking(b,'Expired','automation');notice(s,{key:'hold:'+b.id,rule:'holdExpiry',booking:b.id,title:'Hold berakhir · '+b.guest,body:'Penahanan '+u.name+' untuk '+b.start+' sampai '+b.end+' telah berakhir. Tanggal kembali tersedia.'},iso);continue;}
  const due=balance(s,b);
  if(a.rules.paymentReminder.enabled&&['Confirmed','Checked-in'].includes(b.status)&&b.start<=shift(t,a.rules.paymentReminder.daysBefore)&&b.end>t&&due>0){notice(s,{key:'payment:'+b.id+':'+b.start,rule:'paymentReminder',booking:b.id,title:'Pelunasan · '+b.guest,body:`Halo ${b.guest}, kami mengingatkan sisa pembayaran reservasi ${b.id} di ${s.settings.name} sebesar ${rupiah(due)}. Jadwal check-in ${b.start} pukul ${s.settings.checkin} WITA. Mohon konfirmasi setelah pembayaran. Terima kasih.`},iso);}
  if(a.rules.arrivalPreparation.enabled&&b.status==='Confirmed'&&b.start<=shift(t,a.rules.arrivalPreparation.daysBefore)&&b.end>t){const key='arrival:'+b.id+':'+b.start+':'+b.unit;const old=s.tasks.find(x=>x.sourceKey===key);const draft=`Halo ${b.guest}, kami menantikan kedatangan Anda di ${s.settings.name}, ${u.name}, pada ${b.start}. Check-in mulai pukul ${s.settings.checkin} WITA untuk ${b.guests} tamu. Silakan informasikan perkiraan waktu kedatangan Anda. Terima kasih.`;notice(s,{key,rule:'arrivalPreparation',booking:b.id,title:'Persiapan kedatangan · '+b.guest,body:draft},iso);if(!old){s.tasks.push({id:crypto.randomUUID(),sourceKey:key,unit:b.unit,kind:'Housekeeping',title:'Periksa kesiapan untuk '+b.guest,status:'Belum dikerjakan',assignee:'',due:b.start,bookingId:b.id,readinessImpact:'none',createdAt:iso});automationLog(s,'arrivalPreparation','Tugas persiapan dibuat untuk '+u.name,iso);} }
  if(a.rules.checkoutReminder.enabled&&b.status==='Checked-in'&&b.end<=shift(t,a.rules.checkoutReminder.daysBefore)){notice(s,{key:'departure:'+b.id+':'+b.end,rule:'checkoutReminder',booking:b.id,title:'Jadwal check-out · '+b.guest,body:`Halo ${b.guest}, waktu check-out Anda di ${s.settings.name} adalah ${b.end} pukul ${s.settings.checkout} WITA. Mohon hubungi kami jika memerlukan bantuan. Terima kasih telah menginap.`},iso);}
 }
 for(const plan of a.schedules){if(!plan.enabled||plan.nextDue>t)continue;const key='maintenance:'+plan.id+':'+plan.nextDue;if(!s.tasks.some(x=>x.sourceKey===key)){s.tasks.push({id:crypto.randomUUID(),sourceKey:key,unit:plan.unit,kind:'Maintenance',title:plan.title,status:'Belum dikerjakan',assignee:plan.assignee,due:plan.nextDue,readinessImpact:'none',createdAt:iso});automationLog(s,'maintenance','Perawatan dijadwalkan: '+plan.title+' · '+(s.units.find(u=>u.id===plan.unit)?.name||plan.unit),iso);}const elapsed=Math.floor((Date.parse(t)-Date.parse(plan.nextDue))/86400000);plan.nextDue=shift(plan.nextDue,(Math.floor(elapsed/plan.intervalDays)+1)*plan.intervalDays);}
 // Cancel unfinished preparation work if its reservation was cancelled or moved.
 for(const task of s.tasks){if(!task.sourceKey?.startsWith('arrival:')||task.status==='Selesai')continue;const b=s.bookings.find(x=>task.sourceKey==='arrival:'+x.id+':'+x.start+':'+x.unit);if(!b||!['Confirmed','Checked-in'].includes(b.status))transitionTask(task,'Dibatalkan','automation');}
 a.lastRun=iso;return s;
}

