import type {State} from './pms';
export type Connection={id:string;unit:string;ota:string;listing:string;mode:'ical'|'api';url:string;enabled:boolean;token:string;lastSync:string|null;lastAttempt:string|null;error:string|null;outbound:'pending';};
export type ExternalEvent={id:string;connection:string;uid:string;start:string;end:string;summary:string;status:'active'|'cancelled';updated:string;};
export type Channels={connections:Connection[];events:ExternalEvent[];history:{id:string;time:string;connection:string;message:string;ok:boolean}[];};
export const ensureChannels=(s:State)=>s.channels??={connections:[],events:[],history:[]};
const localDate=(s:string)=>{if(!/^\d{8}$/.test(s))throw Error('Kalender harus menggunakan tanggal sepanjang hari (VALUE=DATE).');const d=s.slice(0,4)+'-'+s.slice(4,6)+'-'+s.slice(6,8);if(!Number.isFinite(Date.parse(d))||new Date(d+'T00:00:00Z').toISOString().slice(0,10)!==d)throw Error('Tanggal kalender tidak valid.');return d};
export type ParsedEvent={uid:string;start?:string;end?:string;summary:string;cancelled:boolean};
export function parseCalendar(raw:string):ParsedEvent[]{if(raw.length>1000000)throw Error('Kalender terlalu besar.');const lines=raw.replace(/^\uFEFF/,'').replace(/\r\n/g,'\n').replace(/\n[ \t]/g,'').trim().split('\n');if(lines[0]!=='BEGIN:VCALENDAR'||lines.at(-1)!=='END:VCALENDAR')throw Error('Respons bukan kalender iCal yang valid.');const out:ParsedEvent[]=[];let current:Record<string,string>|null=null;for(const line of lines){if(line==='BEGIN:VEVENT'){if(current)throw Error('Struktur kalender tidak valid.');current={};continue}if(line==='END:VEVENT'){if(!current||!current.UID)throw Error('Event kalender tidak memiliki UID.');if(current.RRULE||current['RECURRENCE-ID'])throw Error('Kalender berulang belum didukung; data sebelumnya dipertahankan.');if(!current.UID.endsWith('@vila-eight')&&current['X-VILA-EIGHT-ORIGIN']!=='1'){const cancelled=current.STATUS==='CANCELLED';const start=current.DTSTART?localDate(current.DTSTART):undefined,end=current.DTEND?localDate(current.DTEND):undefined;if(!cancelled&&(!start||!end||end<=start))throw Error('Event harus memiliki tanggal mulai dan selesai yang valid.');out.push({uid:current.UID,start,end,summary:(current.SUMMARY||'Tanggal tidak tersedia').replace(/\\n/gi,' ').replace(/\\([,;\\])/g,'$1').slice(0,200),cancelled});}current=null;continue}if(current){const colon=line.indexOf(':');if(colon<0)continue;const key=line.slice(0,colon).split(';')[0].toUpperCase();if(key in current&&['UID','DTSTART','DTEND'].includes(key))throw Error('Event mengandung data rangkap.');current[key]=line.slice(colon+1);}}if(current)throw Error('Kalender terpotong; data sebelumnya dipertahankan.');if(out.length>2000||new Set(out.map(x=>x.uid)).size!==out.length)throw Error('Jumlah event terlalu banyak atau UID duplikat.');return out;}
export function mergeCalendar(s:State,connectionId:string,events:ParsedEvent[],now=new Date().toISOString()){const c=ensureChannels(s);const seen=new Set(events.map(x=>x.uid));for(const old of c.events.filter(e=>e.connection===connectionId)){if(!seen.has(old.uid)){old.status='cancelled';old.updated=now;}}for(const event of events){const old=c.events.find(e=>e.connection===connectionId&&e.uid===event.uid);if(event.cancelled){if(old){old.status='cancelled';old.updated=now;}continue;}const update={start:event.start!,end:event.end!,summary:event.summary,status:'active' as const,updated:now};if(old)Object.assign(old,update);else c.events.push({...update,id:crypto.randomUUID(),connection:connectionId,uid:event.uid});}const conn=c.connections.find(x=>x.id===connectionId);if(conn){conn.lastSync=now;conn.lastAttempt=now;conn.error=null;}c.history.unshift({id:crypto.randomUUID(),time:now,connection:connectionId,message:events.filter(x=>!x.cancelled).length+' blok tanggal berhasil diimpor',ok:true});c.history=c.history.slice(0,300);}
export const externalBlocks=(s:State,unit:string)=>{const c=ensureChannels(s);return c.events.filter(e=>e.status==='active'&&c.connections.some(x=>x.id===e.connection&&x.unit===unit));};
export function exportCalendar(s:State,connectionId:string){const c=ensureChannels(s),dest=c.connections.find(x=>x.id===connectionId);if(!dest)throw Error('Listing tidak ditemukan.');const entries:{id:string;start:string;end:string}[]=[];for(const b of s.bookings){if(b.unit===dest.unit&&(['Confirmed','Checked-in'].includes(b.status)||(b.status==='Hold'&&b.holdUntil&&Date.parse(b.holdUntil)>Date.now())))entries.push({id:'booking-'+b.id,start:b.start,end:b.end});}for(const b of s.blocks)if(b.unit===dest.unit)entries.push({id:'block-'+b.id,start:b.start,end:b.end});for(const e of externalBlocks(s,dest.unit))if(e.connection!==dest.id)entries.push({id:'external-'+e.id,start:e.start,end:e.end});const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Vila Eight//Availability//ID','CALSCALE:GREGORIAN','METHOD:PUBLISH',...entries.flatMap(e=>['BEGIN:VEVENT','UID:'+e.id+'@vila-eight','DTSTAMP:'+stamp,'DTSTART;VALUE=DATE:'+e.start.replace(/-/g,''),'DTEND;VALUE=DATE:'+e.end.replace(/-/g,''),'SUMMARY:Unavailable','X-VILA-EIGHT-ORIGIN:1','END:VEVENT']),'END:VCALENDAR',''].join('\r\n');}
const hosts:Record<string,string[]>={'Airbnb':['airbnb.com'],'Booking.com':['booking.com'],'Vrbo':['vrbo.com','homeaway.com']};
export function validateCalendarUrl(ota:string,value:string){let u:URL;try{u=new URL(value)}catch{throw Error('URL kalender tidak valid.')}if(u.protocol!=='https:'||u.username||u.password||(u.port&&u.port!=='443')||!hosts[ota]?.some(h=>u.hostname===h||u.hostname.endsWith('.'+h)))throw Error('Gunakan URL ekspor HTTPS resmi Airbnb, Booking.com, atau Vrbo. Kanal lain memerlukan adapter yang diverifikasi.');return u.href;}
export async function fetchCalendar(conn:Connection){const url=validateCalendarUrl(conn.ota,conn.url);const r=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(15000),headers:{Accept:'text/calendar'}});if(!r.ok||!r.body)throw Error('OTA tidak mengembalikan kalender. Periksa URL ekspor dan status listing.');const reader=r.body.getReader();let bytes=0;const chunks:Uint8Array[]=[];for(;;){const {done,value}=await reader.read();if(done)break;bytes+=value.length;if(bytes>1000000){await reader.cancel();throw Error('Ukuran kalender melebihi batas.');}chunks.push(value)}const all=new Uint8Array(bytes);let i=0;for(const chunk of chunks){all.set(chunk,i);i+=chunk.length;}return parseCalendar(new TextDecoder().decode(all));}
export function connectionMutation(s:State,action:string,p:any){const c=ensureChannels(s);if(action==='channel-update'){const conn=c.connections.find(x=>x.id===p.id);if(!conn)throw Error('Listing tidak ditemukan.');if(conn.mode==='ical')conn.url=validateCalendarUrl(conn.ota,p.url);conn.error=null;conn.lastAttempt=null;}else if(action==='channel-add'){if(!s.units.some(u=>u.id===p.unit))throw Error('Unit tidak ditemukan.');if(!['Airbnb','Booking.com','Agoda','Traveloka','Vrbo','Lainnya'].includes(p.ota))throw Error('OTA tidak valid.');if(typeof p.listing!=='string'||!p.listing.trim()||p.listing.length>150)throw Error('Masukkan ID atau nama listing.');if(c.connections.some(x=>x.ota===p.ota&&x.listing===p.listing.trim()))throw Error('Listing ini sudah dipetakan.');if(c.connections.length>=64)throw Error('Maksimal 64 pemetaan listing.');const mode=p.mode==='ical'?'ical':'api';const url=mode==='ical'?validateCalendarUrl(p.ota,p.url):'';c.connections.push({id:crypto.randomUUID(),unit:p.unit,ota:p.ota,listing:p.listing.trim(),mode,url,enabled:true,token:crypto.randomUUID().replace(/-/g,'')+crypto.randomUUID().replace(/-/g,''),lastSync:null,lastAttempt:null,error:null,outbound:'pending'});}else if(action==='channel-toggle'){const conn=c.connections.find(x=>x.id===p.id);if(!conn||typeof p.enabled!=='boolean')throw Error('Listing tidak valid.');conn.enabled=p.enabled;}else throw Error('Tindakan kanal tidak dikenal.');return s;}
export async function tokenHash(token:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
export function simulateChannels(s:State,unit:string,event:string){if(!s.units.some(u=>u.id===unit)||!['create','move','cancel'].includes(event))throw Error('Simulasi tidak valid.');const c=ensureChannels(s);for(const ota of ['Airbnb','Booking.com','Agoda','Traveloka'])if(!c.connections.some(x=>x.unit===unit&&x.listing==='SIMULASI-'+unit+'-'+ota))connectionMutation(s,'channel-add',{unit,ota,listing:'SIMULASI-'+unit+'-'+ota,mode:'api'});const source=c.connections.find(x=>x.listing==='SIMULASI-'+unit+'-Airbnb')!;const now=new Date();const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Makassar',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);const shift=(n:number)=>new Date(Date.parse(day+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);mergeCalendar(s,source.id,event==='cancel'?[]:[{uid:'simulated-'+unit,start:shift(event==='move'?4:1),end:shift(event==='move'?6:3),summary:'SIMULASI — Reservasi Airbnb',cancelled:false}]);return s;}

