import {externalBlocks,connectionMutation,simulateChannels} from './channels.ts';
import type {Channels} from './channels.ts';
import {ensureAutomation,automationLog,defaultAutomation} from './automation.ts';
import type {AutomationData,RuleKey} from './automation.ts';
import {blocksAvailability,canTransitionBookingStatus,transitionBooking} from './booking-status.ts';
import type {BookingStatus,BookingStatusEvent} from './booking-status.ts';
export type Unit={id:string;name:string;capacity:number;rate:number;clean:string};
export type Booking={id:string;unit:string;guest:string;phone:string;start:string;end:string;guests:number;channel:string;status:BookingStatus;statusHistory?:BookingStatusEvent[];total:number;note:string;created:string;holdUntil?:string;guestId?:string};
export type Payment={id:string;booking:string;amount:number;type:string;method:string;date:string;note:string};
export type Task={id:string;unit:string;kind:string;title:string;status:string;assignee:string;due:string;sourceKey?:string};
export type Block={id:string;unit:string;start:string;end:string;reason:string};
export type Expense={id:string;unit:string;category:string;amount:number;date:string;note:string};
export type Guest={id:string;name:string;phone?:string;email?:string;nationality?:string;notes?:string;createdAt:string;updatedAt:string};
export type State={channels?:Channels;automation?:AutomationData;units:Unit[];bookings:Booking[];payments:Payment[];tasks:Task[];blocks:Block[];expenses:Expense[];guests?:Guest[];audit:{id:string;date:string;action:string}[];settings:{name:string;checkin:string;checkout:string};};
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Makassar',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const addDays=(d:string,n:number)=>Number.isFinite(Date.parse(d+'T00:00:00Z'))?new Date(Date.parse(d+'T00:00:00Z')+n*86400000).toISOString().slice(0,10):'';
export const nights=(a:string,b:string)=>Math.round((Date.parse(b+'T00:00:00Z')-Date.parse(a+'T00:00:00Z'))/86400000);
export const money=(v:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v);
export const active=(b:Booking)=>blocksAvailability(b);
export const paid=(s:State,id:string)=>s.payments.filter(p=>p.booking===id&&['payment','refund'].includes(p.type)).reduce((a,p)=>a+(p.type==='refund'?-p.amount:p.amount),0);
export function ensureGuests(s:State):Guest[]{if(!Array.isArray(s.guests))s.guests=[];return s.guests}
export const normName=(v:string)=>String(v||'').trim().toLowerCase().replace(/\s+/g,' ');
export const normEmail=(v:string)=>String(v||'').trim().toLowerCase();
function guestBase(g:{name:string,phone?:string|null,email?:string|null}):string{return String(g.name||'').trim()+(g.phone?' — '+g.phone:g.email?' — '+g.email:'')}
export const guestLabel=(g:Guest,all:Guest[]=[])=>{const base=guestBase(g);return all.some(x=>x.id!==g.id&&guestBase(x)===base)?base+' · '+g.id:base}
export function normPhone(v:string){const d=String(v||'').replace(/[^\d]/g,'');if(!d)return'';return d.startsWith('62')&&d.length>10?'0'+d.slice(2):d}
export function linkGuestTransaction(s:State,name:string,phone?:string,email?:string,guestId?:string):string|undefined{const snap=(Array.isArray(s.guests)?s.guests:[]).map(g=>({...g}));const tmp:State={...s,guests:snap};try{const gid=linkGuest(tmp,name,phone,email,guestId);if(!gid)return undefined;s.guests=tmp.guests;return gid}catch{return undefined}}
export function matchGuest(g:Guest[],name:string,phone?:string,email?:string):Guest|undefined{const n=normName(name);if(!n)return undefined;if(email){const e=normEmail(email);if(e){const f=g.find(x=>x.email&&normEmail(x.email)===e&&normName(x.name)===n);if(f)return f}}if(phone){const ph=normPhone(phone);if(ph){const f=g.find(x=>x.phone&&normPhone(x.phone)===ph&&normName(x.name)===n);if(f)return f}}return undefined}
export function linkGuest(s:State,name:string,phone?:string,email?:string,guestId?:string):string|undefined{const gs=ensureGuests(s),now=new Date().toISOString();if(guestId){const ex=gs.find(x=>x.id===guestId);if(ex){ex.updatedAt=now;return ex.id}}const found=matchGuest(gs,name,phone,email);if(found){found.updatedAt=now;return found.id}const nid='GST-'+crypto.randomUUID().slice(0,8).toUpperCase();gs.push({id:nid,name:String(name||'').trim().slice(0,100),phone:phone||'',email:email||'',createdAt:now,updatedAt:now});return nid}
export function initial(demo=false):State{const t=today(); const s:State={units:Array.from({length:8},(_,i)=>({id:'v'+(i+1),name:'Vila '+String(i+1).padStart(2,'0'),capacity:4,rate:1500000,clean:'Siap'})),bookings:[],payments:[],tasks:[],blocks:[],expenses:[],audit:[],settings:{name:'Vila Eight',checkin:'14:00',checkout:'12:00'}}; if(demo){['Ayu Putri','Daniel Hartono','Nadia Pratama','Raka Wijaya','Sofia Tan'].forEach((guest,i)=>{const b:Booking={id:'DEMO-'+(101+i),unit:'v'+(i+1),guest,phone:'',start:addDays(t,i<3?-1:i-3),end:addDays(t,i+2),guests:2,channel:['Langsung','Airbnb','Booking.com'][i%3],status:i<3?'Checked-in':'Confirmed',total:(i<3?i+3:5)*1500000,note:'Reservasi contoh',created:t};b.total=nights(b.start,b.end)*1500000;s.bookings.push(b);s.payments.push({id:'dp'+i,booking:b.id,amount:i%2?b.total/2:b.total,type:'payment',method:'Transfer',date:t,note:'Contoh'});});s.tasks.push({id:'task1',unit:'v6',kind:'Housekeeping',title:'Persiapan kedatangan',status:'Belum dikerjakan',assignee:'Tim operasional',due:t});s.units[5].clean='Perlu dibersihkan';} return s;}
function check(ok:unknown,msg:string):asserts ok {if(!ok)throw Error(msg)}
function str(v:unknown,max=300){check(typeof v==='string'&&v.trim().length>0&&v.length<=max,'Isian wajib belum lengkap atau terlalu panjang.');return v.trim()}
function amount(v:unknown){const n=Number(v);check(Number.isSafeInteger(n)&&n>=0&&n<=1e12,'Nominal harus berupa rupiah bulat positif.');return n}
function date(v:unknown){const d=str(v,10);check(/^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d))&&new Date(d+'T00:00:00Z').toISOString().slice(0,10)===d,'Tanggal tidak valid.');return d}
function range(a:unknown,b:unknown){const start=date(a),end=date(b);check(end>start&&nights(start,end)<=365,'Check-out harus setelah check-in, maksimal 365 malam.');return {start,end}}
function available(s:State,u:string,start:string,end:string,id=''){check(!s.bookings.some(b=>b.id!==id&&b.unit===u&&active(b)&&b.start<end&&b.end>start)&&!s.blocks.some(b=>b.unit===u&&b.start<end&&b.end>start)&&!externalBlocks(s,u).some(b=>b.start<end&&b.end>start),'Unit sudah dipesan atau diblokir pada tanggal tersebut.');}
export function mutate(source:State,action:string,p:any):State {const s=structuredClone(source);const automation=ensureAutomation(s);const id=()=>crypto.randomUUID();const unit=(u:string)=>{const x=s.units.find(v=>v.id===u);check(x,'Unit tidak ditemukan.');return x};const booking=()=>{const b=s.bookings.find(b=>b.id===p.id);check(b,'Reservasi tidak ditemukan.');return b};
 if(action==='booking'){const u=unit(p.unit);const r=range(p.start,p.end);available(s,u.id,r.start,r.end,p.id);const guests=Number(p.guests);check(Number.isInteger(guests)&&guests>=1&&guests<=u.capacity,'Jumlah tamu melebihi kapasitas unit.');const b=p.id?booking():null;check(!b||['Confirmed','Hold'].includes(b.status),'Reservasi ini tidak dapat diubah.');const total=amount(p.total);check(!b||total>=paid(s,b.id),'Total baru lebih kecil dari pembayaran. Proses refund terlebih dahulu.');const data={unit:u.id,guest:str(p.guest,100),phone:String(p.phone||'').slice(0,50),...r,guests,channel:str(p.channel,50),total,note:String(p.note||'').slice(0,1000)};let target:Booking;if(b){Object.assign(b,data);target=b}else{target={...data,id:'RSV-'+id().slice(0,8).toUpperCase(),status:p.hold?'Hold':'Confirmed',created:new Date().toISOString(),...(p.hold?{holdUntil:new Date(Date.now()+3600000).toISOString()}: {})};s.bookings.push(target)}try{const gid=linkGuest(s,target.guest,target.phone||undefined,String(p.email||'')||undefined,p.guestId);if(gid)target.guestId=gid}catch{};
 }else if(action==='status'){const b=booking();const u=unit(b.unit);const target=String(p.status||'');check(canTransitionBookingStatus(b.status,target),'Perubahan status tidak diperbolehkan.');if(target==='Confirmed')available(s,b.unit,b.start,b.end,b.id);if(target==='Checked-in'){check(u.clean==='Siap','Unit belum siap. Selesaikan housekeeping terlebih dahulu.');check(b.start<=today()&&b.end>today(),'Check-in hanya dapat dilakukan dalam tanggal menginap.');}if(target==='No-show')check(b.start<=today(),'No-show hanya dapat dicatat pada atau setelah tanggal kedatangan.');if(!transitionBooking(b,target as BookingStatus,'operator'))throw Error('Perubahan status tidak diperbolehkan.');if(target==='Checked-out'){u.clean='Perlu dibersihkan';if(automation.rules.checkoutCleanup.enabled&&!s.tasks.some(x=>x.sourceKey==='checkout:'+b.id)){s.tasks.push({id:id(),sourceKey:'checkout:'+b.id,unit:u.id,kind:'Housekeeping',title:'Pembersihan setelah '+b.guest,status:'Belum dikerjakan',assignee:'',due:today()});automationLog(s,'checkoutCleanup','Pembersihan otomatis dibuat untuk '+u.name);}}
 }else if(action==='payment'){const b=booking(),n=amount(p.amount);check(n>0,'Nominal harus lebih dari nol.');check(['payment','refund','deposit','deposit-return'].includes(p.type),'Jenis transaksi tidak valid.');const dep=s.payments.filter(x=>x.booking===b.id).reduce((a,x)=>a+(x.type==='deposit'?x.amount:x.type==='deposit-return'?-x.amount:0),0);if(p.type==='refund')check(n<=paid(s,b.id),'Refund melebihi pembayaran bersih.');if(p.type==='payment')check(n<=b.total-paid(s,b.id),'Pembayaran melebihi sisa tagihan.');if(p.type==='deposit-return')check(n<=dep,'Pengembalian melebihi deposit.');s.payments.push({id:id(),booking:b.id,amount:n,type:p.type,method:str(p.method,50),date:date(p.date),note:String(p.note||'').slice(0,300)});
 }else if(action==='task'){unit(p.unit);check(['Housekeeping','Maintenance'].includes(p.kind),'Jenis tugas tidak valid.');s.tasks.push({id:id(),unit:p.unit,kind:p.kind,title:str(p.title),status:'Belum dikerjakan',assignee:String(p.assignee||'').slice(0,100),due:date(p.due)});if(p.kind==='Housekeeping')unit(p.unit).clean='Perlu dibersihkan';
 }else if(action==='task-status'){const t=s.tasks.find(t=>t.id===p.id);check(t,'Tugas tidak ditemukan.');check(['Dikerjakan','Menunggu pemeriksaan','Selesai'].includes(p.status),'Status tidak valid.');t.status=p.status;if(t.kind==='Housekeeping')unit(t.unit).clean=s.tasks.some(x=>x.unit===t.unit&&x.kind==='Housekeeping'&&!['Selesai','Dibatalkan'].includes(x.status))?'Perlu dibersihkan':'Siap';
 }else if(action==='block'){unit(p.unit);const r=range(p.start,p.end);available(s,p.unit,r.start,r.end);s.blocks.push({id:id(),unit:p.unit,...r,reason:str(p.reason)});
 }else if(action==='unblock'){check(s.blocks.some(b=>b.id===p.id),'Blokir tidak ditemukan.');s.blocks=s.blocks.filter(b=>b.id!==p.id);
 }else if(action==='expense'){if(p.unit)unit(p.unit);s.expenses.push({id:id(),unit:p.unit||'',category:str(p.category,80),amount:amount(p.amount),date:date(p.date),note:str(p.note)});
 }else if(action==='unit'){const u=unit(p.id);u.name=str(p.name,80);u.rate=amount(p.rate);const c=Number(p.capacity);check(Number.isInteger(c)&&c>=1&&c<=50,'Kapasitas harus 1–50.');u.capacity=c;
 }else if(action==='settings'){s.settings={name:str(p.name,80),checkin:str(p.checkin,5),checkout:str(p.checkout,5)};
 }else if(action==='guest'){const gs=ensureGuests(s),now=new Date().toISOString(),g=p.id?gs.find(x=>x.id===p.id):null;if(p.id)check(g,'Tamu tidak ditemukan.');const name=str(p.name,100);if(g){g.name=name;g.phone=p.phone?str(p.phone,50):'';g.email=p.email?str(p.email,120):'';g.nationality=p.nationality?str(p.nationality,60):'';g.notes=p.notes?String(p.notes||'').slice(0,500):'';g.updatedAt=now}else gs.push({id:'GST-'+id().slice(0,8).toUpperCase(),name,phone:p.phone?str(p.phone,50):'',email:p.email?str(p.email,120):'',nationality:p.nationality?str(p.nationality,60):'',notes:p.notes?String(p.notes||'').slice(0,500):'',createdAt:now,updatedAt:now})}else if(action==='channel-demo'){simulateChannels(s,p.unit,p.event);
 }else if(action==='channel-add'||action==='channel-toggle'||action==='channel-update'){connectionMutation(s,action,p);
 }else if(action==='automation-rule'){check(Object.hasOwn(defaultAutomation().rules,p.key),'Aturan tidak ditemukan.');check(typeof p.enabled==='boolean','Status aturan tidak valid.');const n=Number(p.daysBefore);check(Number.isInteger(n)&&n>=0&&n<=30,'Jeda pengingat harus 0–30 hari.');automation.rules[p.key as RuleKey]={enabled:p.enabled,daysBefore:n};
 }else if(action==='automation-notice'){const n=automation.notices.find(n=>n.id===p.id);check(n,'Pengingat tidak ditemukan.');check(['read','resolved'].includes(p.status),'Status pengingat tidak valid.');n.status=p.status;
 }else if(action==='automation-schedule'){unit(p.unit);const intervalDays=Number(p.intervalDays);check(Number.isInteger(intervalDays)&&intervalDays>=1&&intervalDays<=365,'Interval harus 1–365 hari.');const schedule={unit:p.unit,title:str(p.title),assignee:String(p.assignee||'').slice(0,100),nextDue:date(p.nextDue),intervalDays,enabled:true};if(p.id){const existing=automation.schedules.find(x=>x.id===p.id);check(existing,'Jadwal tidak ditemukan.');Object.assign(existing,schedule);}else automation.schedules.push({id:id(),...schedule});
 }else if(action==='automation-schedule-toggle'){const schedule=automation.schedules.find(x=>x.id===p.id);check(schedule,'Jadwal tidak ditemukan.');check(typeof p.enabled==='boolean','Status jadwal tidak valid.');schedule.enabled=p.enabled;
 }else throw Error('Tindakan tidak dikenali.');
 s.audit.unshift({id:id(),date:new Date().toISOString(),action:action+' · '+(p.guest||p.title||p.id||p.name||p.category||p.reason||'Perubahan data')});s.audit=s.audit.slice(0,1000);return s;
}




